# Generated by Django 5.1.2 on 2024-12-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.IntegerField()),
                ('p_compony', models.CharField(max_length=100)),
                ('p_is_sale', models.BooleanField(default=False)),
                ('p_description', models.CharField(max_length=1500)),
                ('slug', models.SlugField()),
                ('color_variant', models.ManyToManyField(blank=True, to='products.colorvariant')),
                ('p_child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='categories.child_category')),
                ('p_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='categories.gender')),
                ('size_variant', models.ManyToManyField(blank=True, to='products.sizevariant')),
            ],
        ),
    ]
