# Generated by Django 5.1.2 on 2024-12-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('i_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=300)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product')),
            ],
        ),
    ]
