# Generated by Django 5.1.2 on 2025-01-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_gender_g_name'),
        ('products', '0003_alter_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_child_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.child_category'),
        ),
    ]
