# Generated by Django 5.1.2 on 2025-01-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_image', to='products.product'),
        ),
    ]
