# Generated by Django 5.1.2 on 2024-12-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('g_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='parent_category',
            fields=[
                ('p_c_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('p_c_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='child_category',
            fields=[
                ('c_c_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('c_c_name', models.CharField(max_length=100, unique=True)),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='categories.parent_category')),
            ],
        ),
    ]
