# Generated by Django 5.1.2 on 2024-12-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='g_name',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
