# Generated by Django 5.1.2 on 2024-12-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_gender_g_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='g_name',
            field=models.CharField(max_length=200),
        ),
    ]
