# Generated by Django 5.1.5 on 2025-01-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_gender_g_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='g_name',
            field=models.IntegerField(),
        ),
    ]
