# Generated by Django 5.1.5 on 2025-01-21 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_alter_product_p_child_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyed_history',
            fields=[
                ('b_h_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('b_h_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to='products.product')),
                ('b_h_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
